/**
 * Catalog of all book images available in /static/book-images/.
 * These are served to the AI as a reference list so it can pick the most
 * relevant image(s) per finding. Descriptions are drawn from the book's
 * visual arguments — what the image shows and why it matters.
 *
 * BOOK_IMAGE_MAP is used server-side to validate AI-returned filenames
 * and to attach the caption to each selected image.
 */

/**
 * pair: the natural companion image — a ❌/✅ before/after set designed
 *       to be shown together. The server auto-includes the pair if the AI
 *       selects one image without its partner.
 */
/** @typedef {{ src: string, desc: string, tags: string[], pair?: string }} BookImageEntry */

/** @type {BookImageEntry[]} */
export const BOOK_IMAGES = [

    // ── Visual Hierarchy ──────────────────────────────────────────────────────
    { src: 'image44.png', tags: ['Visual Hierarchy'], desc: 'used to show how not using background color to every content area makes a difference. if a sidebar feels like it\'s competing with your main content area, don\'t give it a background color — let the content sit directly on the page background instead. show this image only if there is background color in content area.' },
    { src: 'image51.png', tags: ['Visual Hierarchy', 'Typography'], desc: 'used to show how an oversized section heading harms hierarchy. A default large heading can outweigh the content it introduces — labels should be quieter than what they label. show this image only if heading size is big.' },
    { src: 'image52.png', tags: ['Visual Hierarchy', 'Typography'], desc: 'used to show how reducing a heading\'s visual weight makes a difference. Reducing a section heading to small pale text lets the actual controls become the most prominent elements on the page. show this image only if heading size is big.' },
    { src: 'image53.png', tags: ['Visual Hierarchy'], desc: 'used to show how hierarchy without prominent headings makes a difference. Strong hierarchy can exist without prominent headings when content uses size, weight, and spacing differences. show this image only if heading size is big.' },
    { src: 'image58.png', pair: 'image59.png', tags: ['Visual Hierarchy', 'Interactive Targets'], desc: 'used to show how equal-weight button styles harm action hierarchy. Three equal-weight filled buttons offer no signal about which action is primary — the user must read every label. shown together with image59. show this only if there are 2 or more buttons next to each with same weight inside of a container/label.' },
    { src: 'image59.png', pair: 'image58.png', tags: ['Visual Hierarchy', 'Interactive Targets'], desc: 'used to show how button style hierarchy (filled/outlined/text) makes a difference. Using filled, outlined, and text-only button styles creates an instant primary → secondary → tertiary action hierarchy.' },
    { src: 'image61.jpeg', pair: 'image62.jpeg', tags: ['Visual Hierarchy', 'Interactive Targets'], desc: 'used to show how limiting dominant actions per section makes a difference. Limiting each section to one dominant action prevents the page from feeling like every option matters equally. show this only if there is a button with destructive action, together with image62' },
    { src: 'image62.jpeg', pair: 'image61.jpeg', tags: ['Visual Hierarchy', 'Interactive Targets'], desc: 'used to show how styling a destructive action as a plain text link makes a difference. A dangerous action styled as a plain text link is still findable but draws no alarming attention.' },

    // ── Colour Palette / Text Contrast ────────────────────────────────────────
    { src: 'image37.png', pair: 'image38.jpeg', tags: ['Colour Palette', 'Typography'], desc: 'used to show how colour lightness in secondary text makes a difference. Making text a lighter grey is a great way to de-emphasize it on white backgrounds, but it doesn\'t look so great on colored backgrounds. That\'s because the effect we\'re actually seeing with grey on white is reduced contrast. show this together with image38,39,40,41, only if there is gray/gray-shaded text on colored background.' },
    { src: 'image38.jpeg', tags: ['Colour Palette'], desc: 'used to show how grey text on a coloured card background makes a difference. Making the text closer to the background color is what actually helps create hierarchy, not making it light grey.' },
    { src: 'image39.jpeg', tags: ['Colour Palette'], desc: 'used to show how the same grey value reads differently on white vs coloured surfaces. You might think that the easiest way to achieve this is to use white text and reduce the opacity. While this does reduce the contrast, it often results in text that looks dull, washed out, and sometimes even disabled.' },
    { src: 'image40.jpeg', pair: 'image41.png', tags: ['Colour Palette'], desc: 'used to show how grey secondary text on a coloured card creates unintended contrast. Even worse, using this approach on top of an image or pattern means the background will show through the text.' },
    { src: 'image41.png', pair: 'image40.jpeg', tags: ['Colour Palette'], desc: 'used to show how hue-matched tinted text on a coloured card makes a difference. A better approach is to hand-pick a new color, based on the background color. Choose a color with the same hue, and adjust the saturation and lightness until it looks right to you. Hand-picking a color this way makes it easy to reduce the contrast without the text looking faded.' },
    { src: 'image151.jpeg', pair: 'image152.jpeg', tags: ['Colour Palette'], desc: 'used to show how a complete UI colour palette is structured. A real UI needs a full grey scale, a primary hue scale, and accent colours for info, warning, error, and success. To build something real, you need a much more comprehensive set of colors to choose from. show this if the whole UI has only 4-5 different colors. show together with image152.' },
    { src: 'image152.jpeg', pair: 'image153.png', tags: ['Colour Palette'], desc: 'used to show how having only three grey shades falls short. Three grey shades look like enough until you try to cover every text level, border, background, and disabled state. show this image only if the UI has only 1-2 grays. shown together with image153.' },
    { src: 'image153.png', tags: ['Colour Palette'], desc: 'used to show how a full 9-shade grey scale makes a difference. A complete 9-shade grey scale covers every text level, surface, border, and disabled state a real UI needs.' },
    { src: 'image154.png', tags: ['Colour Palette'], desc: 'used to show primary colors are the colors that determine the overall look of a site — the ones that make you think of Facebook as "blue". Ultra-light shades can be useful as a tinted background for things like alerts, while darker shades work great for text. show this image only if the UI has 1-2 colors.' },
    { src: 'image155.png', tags: ['Colour Palette'], desc: 'used to show how semantic accent colours for status states make a difference. Separate accent colours for info, warning, error, and success let feedback states communicate meaning without ambiguity. show this image if there are no accent colors in UI. together with image156, 157, 158.' },
    { src: 'image156.jpeg', pair: 'image155.png', tags: ['Colour Palette'], desc: 'used to show You might also need colors to emphasize different semantic states, like red for confirming a destructive action. shown only with when image155 is shown.' },
    { src: 'image157.png', pair: 'image155.png', tags: ['Colour Palette'], desc: 'You might also need colors to emphasize different semantic states, like yellow for a warning message. shown only with when image155 is shown.' },
    { src: 'image158.png', pair: 'image155.png', tags: ['Colour Palette'], desc: 'You might also need colors to emphasize different semantic states, like green to highlight a positive trend. shown only with when image155 is shown.' },
    { src: 'image180.png', pair: 'image181.png', tags: ['Colour Palette'], desc: 'used to show how adding cool blue saturation to grey makes it feel crisp. Adding a hint of blue saturation to grey makes it feel crisp and airy rather than lifeless. show this only if there is natural grays in UI. together with image181.' },
    { src: 'image181.png', pair: 'image180.png', tags: ['Colour Palette'], desc: 'used to show how adding warm yellow-orange saturation to grey makes it feel inviting. Adding a hint of yellow-orange saturation to grey makes it feel warm and inviting rather than cold.' },
    { src: 'image183.png', pair: 'image185.png', tags: ['Colour Palette', 'Readability'], desc: 'used to show how WCAG contrast ratio levels make a difference. There is a visible brightness gap between a failing 3.5:1 ratio, an AA-passing 5.4:1, and an AAA-passing 7.6:1. show this image only if there is such bad contrast of white text and colored background. together with image185.' },
    { src: 'image185.png', pair: 'image183.png', tags: ['Colour Palette'], desc: 'used to show how dark text on a light tinted background compares to white text on dark. Dark coloured text on a light tinted background is more legible and refined than white text on a dark colour fill. only with image183.' },
    { src: 'image186.png', pair: 'image187.png', tags: ['Colour Palette'], desc: 'used to show how white-on-dark text loses hierarchy when both levels are the same colour. When heading and body text are both white on a dark panel, text hierarchy completely disappears. shown this only if the primary text and the secondary text color look the same. together with image187.' },
    { src: 'image187.png', pair: 'image186.png', tags: ['Colour Palette'], desc: 'used to show how hue-rotated secondary text on a dark panel restores hierarchy. Changing secondary body text to a slightly lighter hue-rotated version of the panel colour restores visible hierarchy while staying on-brand.' },
    { src: 'image188.png', pair: 'image189.png', tags: ['Colour Palette'], desc: 'used to show how colour-only status dots fail colourblind users. Status dots differentiated only by colour are indistinguishable to users who cannot perceive colour differences. show this image together with image189 only if there are metric cards with such colors used.' },
    { src: 'image189.png', pair: 'image188.png', tags: ['Colour Palette'], desc: 'used to show how adding icons alongside coloured status dots improves accessibility. Adding a matching icon alongside each coloured status dot makes the state readable regardless of colour perception.' },
    { src: 'image190.png', pair: 'image191.png', tags: ['Colour Palette'], desc: 'used to show how something like a graph, where each trend line has a different color, try relying on contrast instead of using completely different colors. It\'s much easier for someone who\'s colorblind to tell the difference between light and dark than it is for them to tell the difference between two distinct colors. show this image with image191 only if there are graphs with colors on the page.' },
    { src: 'image191.png', pair: 'image190.png', tags: ['Colour Palette'], desc: 'used to show how It\'s much easier for someone who\'s colorblind to tell the difference between light and dark than it is for them to tell the difference between two distinct colors. show image only with image190.' },

    // ── Spacing & Layout ──────────────────────────────────────────────────────
    { src: 'image63.jpeg', pair: 'image65.jpeg', tags: ['Spacing & Layout'], desc: 'used to show how overall form spacing makes a difference. Without breathing room between element groups, a form feels compressed and stressful to fill out. show this only if there is an element with a lot of text and if the spacing of text inside of an element is small.' },
    { src: 'image65.jpeg', pair: 'image63.jpeg', tags: ['Spacing & Layout'], desc: 'used to show how generous padding and gap makes a design feel more polished. The same content with significantly more padding and gap feels calmer and more professionally finished. show this image only with image63, saying how to solve whitespace in element is to start by giving something way too much space, then remove it until you\'re happy with the result.' },
    { src: 'image72.png', pair: 'image73.png', tags: ['Spacing & Layout'], desc: 'used to show how full-width stretched content makes a difference. Stretching content to fill the full browser width makes line lengths uncomfortable and the layout look sparse. show this only if the input elements are spread out too much, not counting nav bars. shown together with image73.' },
    { src: 'image73.png', pair: 'image72.png', tags: ['Spacing & Layout'], desc: 'used to show how Spreading things out or making things unnecessarily wide just makes an interface harder to interpret.' },
    { src: 'image77.png', pair: 'image78.png', tags: ['Spacing & Layout'], desc: 'used to show how a single-column form on a wide screen wastes horizontal space. A single narrow form column on a wide screen wastes large amounts of horizontal space on both sides. show this image only if there is a form on the page. together with image78.' },
    { src: 'image78.png', pair: 'image77.png', tags: ['Spacing & Layout'], desc: 'used to show how a two-column form layout makes better use of wide screens. Reorganising the same fields into two columns makes better use of horizontal space without harming legibility.' },
    { src: 'image90.png', pair: 'image91.png', tags: ['Spacing & Layout', 'Typography'], desc: 'used to show how There\'s nothing inherently wrong with using relative units like em, but don\'t be fooled into believing that relationships defined this way can remain static — 2.5em might be the perfect headline size on desktop but there\'s no guarantee that it\'ll be the right size on smaller screens. shown together with image91 and image92. show this only if there is text with relative units like "em"' },
    { src: 'image91.png', pair: 'image92.png', tags: ['Typography'], desc: 'Say you reduce the size of your body copy to 14px on small screens to keep the line length in check. Keeping your headlines at 2.5em means a rendered font size of 35px — way too big for a small screen! show together with image90 and 92.' },
    { src: 'image92.png', pair: 'image91.png', tags: ['Typography'], desc: 'A better headline size for small screens might be somewhere between 20px and 24px.' },
    { src: 'image97.png', pair: 'image98.png', tags: ['Spacing & Layout'], desc: 'used to show how label-to-input gap spacing makes a difference. When the gap between a label and its input equals the gap between two separate fields, nothing clusters as a unit. show this image only if there is label-to-input elements in the page. together with image98.' },
    { src: 'image98.png', pair: 'image97.png', tags: ['Spacing & Layout'], desc: 'used to show how label-to-input gap spacing makes a difference. Setting the label-to-input gap much smaller than the field-to-field gap makes each label visually belong to its own input. show this image only if there is label-to-input elements in the page. together with image97.' },
    { src: 'image99.png', tags: ['Spacing & Layout'], desc: 'used to show how spacing above and below a heading makes a difference. Equal space above and below a heading leaves it floating between sections, unclear whether it opens or closes a block. show this image only if there is an article on the page with multiple sections and headings.' },
    { src: 'image100.png', tags: ['Spacing & Layout'], desc: 'used to show when the space between bullets matches the lineheight of a single bullet. show this image only if there is bulleted list on the page.' },
    { src: 'image270.png', pair: 'image273.png', tags: ['Spacing & Layout'], desc: 'used to show how vertical spacing between list items replaces divider lines. Generous vertical spacing between list items does the structural work of a divider line without adding visual noise. show only if there are cards/containers with listed items. together with image273.' },
    { src: 'image273.png', pair: 'image270.png', tags: ['Spacing & Layout'], desc: 'used to show how vertical spacing between page sections replaces divider lines. Using box shadow, different background colors, and bigger spacing is a great way to create distinction between groups of elements without introducing any new UI at all. show this only if image270 is shown.' },

    // ── Typography ────────────────────────────────────────────────────────────
    { src: 'image14.png', tags: ['Typography'], desc: 'used to show how a serif typeface makes a difference. Typography plays a huge part in determining how a design feels. If you want an elegant or classic look, you might want to incorporate a serif typeface in your design. show this image only if we find font that is not that regular.' },
    { src: 'image15.png', tags: ['Typography'], desc: 'used to show how a rounded sans-serif typeface makes a difference. Typography plays a huge part in determining how a design feels. For a playful look, you could use a rounded sans serif. show this image only if we find font that is not that regular.' },
    { src: 'image16.png', tags: ['Typography'], desc: 'used to show how a neutral sans-serif typeface makes a difference. Typography plays a huge part in determining how a design feels. If you\'re going for a plainer look, or want to rely on other elements to provide the personality, a neutral sans serif works great. show this image only if we find font that is not that regular.' },
    { src: 'image23.jpeg', pair: 'image24.jpeg', tags: ['Typography'], desc: 'used to show how a language makes a difference. While not a visual design technique per se, the words you use in an interface have a massive influence on the overall personality. Using a less personal tone might feel more official or professional. show this image only if the language of the text is formal.' },
    { src: 'image24.jpeg', pair: 'image23.jpeg', tags: ['Typography'], desc: 'used to show how a casual friendly copy tone makes a difference. Using friendlier, more casual language makes a site feel, well, friendlier. Words are everywhere in a user interface, and choosing the right ones is just as (if not more) important than choosing the right color or typeface. show this image only if the language of the text is formal.' },
    { src: 'image102.png', pair: 'image105.png', tags: ['Typography'], desc: 'used to show how arbitrary font size choices harm type hierarchy. Arbitrary font sizes chosen one at a time produce a hierarchy that feels accidental and inconsistent. show this only if there is a container/bigger-element with combination of buttons, texts, labels, headings, where spacing between these elements is too random. show together with image105.' },
    { src: 'image105.png', pair: 'image102.png', tags: ['Typography'], desc: 'used to show how a defined type scale makes a difference. Restricting sizing to a defined scale makes the typographic hierarchy feel intentional and easy to scan.' },
    { src: 'image112.png', pair: 'image113.jpeg', tags: ['Typography'], desc: 'used to show how 90–110 character line length makes reading harder. Lines running 90–110 characters force the eye to travel far right and struggle to find the start of the next line. show this only if there is text with long lines, 90-110 chars. shown with image113 and image114.' },
    { src: 'image113.jpeg', pair: 'image114.jpeg', tags: ['Typography'], desc: 'used to show how using A width of 20-35em for line length will get you in the right ballpark. shown with image112 and image114.' },
    { src: 'image114.jpeg', pair: 'image113.jpeg', tags: ['Typography'], desc: 'used to show how Going a bit wider than 75 characters per line can sometimes work too, but be aware that you\'re entering risky territory — stick to the 45-75 range if you want to play it safe.' },
    { src: 'image115.jpeg', pair: 'image116.jpeg', tags: ['Typography'], desc: 'used to show how splitting wide text into columns solves line-length problems. Breaking wide text into two or three columns solves over-long line lengths without removing any content. shown only if the paragraph text is mixed with images or other large components. together with image116.' },
    { src: 'image116.jpeg', pair: 'image115.jpeg', tags: ['Typography'], desc: 'used to show how we can use different widths in the same content area, but the result almost always looks more polished. together with image115.' },
    { src: 'image122.png', pair: 'image123.png', tags: ['Typography'], desc: 'used to show how When lines of text are spaced too tightly, it\'s easy to finish reading a line of text at the right edge of a page then jump your eyes all the way back to the left edge only to be unsure which line is next. shown together with image123 only if there is a large paragraph with tight spacing.' },
    { src: 'image123.png', pair: 'image122.png', tags: ['Typography'], desc: 'used to show how that your line-height and paragraph width should be proportional — narrow content can use a shorter line-height like 1.5, but wide content might need a line-height as tall as 2.' },
    { src: 'image124.png', tags: ['Typography'], desc: 'used to show When text is small, extra line spacing is important because it makes it a lot easier for your eyes to find the next line when the text wraps. show this image only if there is small line spacing in paragraphs with 5+ lines.' },
    { src: 'image125.png', tags: ['Typography'], desc: 'used to show how tight line-height on large display headings makes a difference. Large display text at tight 1.1× line-height feels natural — the eye does not need vertical space to return when lines are short. shown if the spacing of large headline is bigger than 1.' },
    { src: 'image127.png', pair: 'image128.png', tags: ['Typography'], desc: 'used to show how styling links with weight and underline instead of colour makes a difference. Styling links with font weight and a subtle underline instead of colour alone signals interactivity without relying on link-blue. shown with image128 and 129, shown only if there is interface with line of elements where almost everything is a link.' },
    { src: 'image128.png', pair: 'image129.png', tags: ['Typography'], desc: 'used to show how Instead, emphasize most links in a more subtle way, like by just using a heavier font weight or darker color.' },
    { src: 'image129.png', pair: 'image128.png', tags: ['Typography'], desc: 'used to show how Some links might not even need to be emphasized by default at all. If you\'ve got links in your interface that are really ancillary and not part of the main path a user takes through the application, consider adding an underline or changing the color only on hover.' },
    { src: 'image132.png', tags: ['Typography'], desc: 'used to show how center alignment for short header pairs makes a difference. if something is longer than two or three lines, it will almost always look better left-aligned. show this image only if there are elements with more than 2-3 lines and center-alignment.' },
    { src: 'image133.png', tags: ['Typography'], desc: 'used to show how If you\'ve got a few blocks of text you want to center but one of them is a bit too long, the easiest fix is to rewrite the content and make it shorter. show this image if there are 3+ elements side by side where one has 2-3 lines and others might have 6-7 lines of text.' },
    { src: 'image134.png', tags: ['Typography'], desc: 'used to show how right-aligning numbers in a table column makes a difference. Right-aligning numbers in a table column lines up decimal points and digit positions for fast visual comparison. show this only if there is a table on page.' },
    { src: 'image141.png', tags: ['Typography'], desc: 'used to show how letter-spacing on all-caps labels makes a difference. All-caps labels benefit from ~0.08em of added letter-spacing — uniform capitals need more width between them to be legible. show this image only if there is such text.' },

    // ── Visual Weight ─────────────────────────────────────────────────────────
    { src: 'image54.png', pair: 'image55.png', tags: ['Visual Weight'], desc: 'used to show how icons (especially solid ones) are generally pretty "heavy" and cover a lot of surface area. As a result, when you put an icon next to some text, the icon tends to feel emphasized. A small solid-filled icon has more visual surface area than nearby text characters, making it feel disproportionately heavy. show this image together with image55 only if there are icons next to text on the page.' },
    { src: 'image55.png', pair: 'image54.png', tags: ['Visual Weight'], desc: 'used to show how reducing icon fill or contrast balances it with text. Removing the fill or reducing the icon\'s contrast brings it into balance with adjacent text without changing its size.' },

    // ── Interactive Targets ───────────────────────────────────────────────────
    { src: 'image94.png', pair: 'image95.png', tags: ['Interactive Targets'], desc: 'used to show how proportional button padding makes a difference. Proportional em-based padding makes small, medium, and large buttons look like identical scaled copies of each other. show this only if there are small buttons in the page. together with image95.' },
    { src: 'image95.png', pair: 'image94.png', tags: ['Interactive Targets'], desc: 'used to show how non-proportional button padding makes a difference. Non-proportional padding — more on large, less on small — gives each button size a distinct, deliberate character.' },

    // ── Icon & Image Size ─────────────────────────────────────────────────────
    { src: 'image222.png', pair: 'image223.png', tags: ['Icon & Image Size'], desc: 'used to show how overlapping avatar circles without border separation make a difference. Overlapping avatar circles without a border separation blur into each other at the overlap edge. show this image only if there are 4+ avatars next to each other. together with image223.' },
    { src: 'image223.png', pair: 'image222.png', tags: ['Icon & Image Size'], desc: 'used to show how a white border ring on overlapping avatars makes a difference. A 2px white border ring on each avatar creates a clean visible edge wherever circles overlap.' },
    { src: 'image225.png', pair: 'image227.png', tags: ['Icon & Image Size'], desc: 'used to show how text placed directly on a photo without an overlay makes a difference. White text placed directly on a photo is readable over dark areas but completely invisible against bright ones. show this only if there is such text. show this with image227, 228, 229, 230.' },
    { src: 'image227.png', pair: 'image225.png', tags: ['Icon & Image Size'], desc: 'used to show how a dark overlay on a photo improves text contrast. A semi-transparent dark overlay levels the photo\'s brightness so white text maintains consistent contrast everywhere. show this only if there is such text. show this with image225, 228, 229, 230.' },
    { src: 'image228.png', tags: ['Icon & Image Size'], desc: 'used to show how a text-shadow on photo text makes a difference. A subtle text-shadow creates local contrast against both light and dark photo areas without darkening the whole image. show this only if there is such text. show this with image225, 227, 229, 230.' },
    { src: 'image229.png', tags: ['Icon & Image Size'], desc: 'used to show how desaturating and tinting a background photo makes a difference. Desaturating and tinting a background photo with a brand colour makes it cohesive and easier to overlay text on. show this only if there is such text. show this with image225, 227, 228, 230.' },
    { src: 'image230.png', tags: ['Icon & Image Size'], desc: 'used to show how combining desaturation and text-shadow on a photo makes a difference. Combining desaturation, reduced contrast, and a text-shadow gives readable text over any photo regardless of its content. show this only if there is such text. show this with image225, 227, 228, 229.' },
    { src: 'image233.png', pair: 'image234.png', tags: ['Icon & Image Size'], desc: 'used to show how scaling an icon up to 3x or 4x their intended size makes a difference. They lack detail, and always feel disproportionately "chunky". show this only if there are icons with 40+px size. together with image234 and image235.' },
    { src: 'image234.png', pair: 'image235.png', tags: ['Icon & Image Size'], desc: 'used to show how placing a small icon inside a larger coloured container makes a difference. Keeping the icon at its native small size inside a bigger coloured container provides visual footprint without distorting the icon. shown together with image235.' },
    { src: 'image235.png', tags: ['Icon & Image Size'], desc: 'used to show how the icon-in-container technique scales independently. The icon stays at its native size while the coloured container scales independently to whatever size is needed.' },
    { src: 'image242.png', pair: 'image243.png', tags: ['Icon & Image Size'], desc: 'used to show how variable-height card images break grid alignment. Portrait photos at their natural aspect ratios make some cards much taller than others, breaking grid alignment. show this only if there are user-uploaded images displayed in some elements. together with image243.' },
    { src: 'image243.png', pair: 'image242.png', tags: ['Icon & Image Size'], desc: 'used to show how fixed-aspect-ratio containers keep a card grid uniform. Fixed-aspect-ratio CSS containers keep all cards the same height regardless of the original photo dimensions. only if image242 is shown.' },

    // ── Depth / Shadows ───────────────────────────────────────────────────────
    { src: 'image205.png', tags: ['Interactive Targets', 'Visual Hierarchy'], desc: 'used to show how a small button drop shadow makes a difference. A small drop shadow makes a button feel slightly raised off the surface, inviting interaction without being dramatic. show image if buttons don\'t have shades.' },
    { src: 'image206.png', tags: ['Visual Hierarchy', 'Spacing & Layout'], desc: 'used to show how a medium shadow on a dropdown or popover makes a difference. A medium drop shadow places a dropdown or popover clearly above the page while keeping it connected to it. show image only if dropdowns don\'t have shades.' },
    { src: 'image207.png', tags: ['Visual Hierarchy', 'Spacing & Layout'], desc: 'used to show how a large shadow on a modal makes a difference. A large drop shadow on a modal communicates maximum elevation and that background content is blocked. show image only if there are modal dialogs without shades.' },
    { src: 'image219.png', pair: 'image220.png', tags: ['Visual Hierarchy', 'Spacing & Layout'], desc: 'used to show how a card overlapping its container boundary makes a difference. A card overlapping its container boundary creates a strong depth illusion and communicates a relationship between the two. show this only if there are no overlapping elements on the page. together with image220.' },
    { src: 'image220.png', pair: 'image219.png', tags: ['Visual Hierarchy', 'Spacing & Layout'], desc: 'used to show how a card crossing a section boundary makes a difference. Offsetting a card to cross a section boundary visually connects the card to its containing section.' },

    // ── Visual Polish / Finishing Touches ─────────────────────────────────────
    { src: 'image248.png', pair: 'image249.jpeg', tags: ['Visual Hierarchy'], desc: 'used to show how small accent details transform default-styled components. A coloured accent border, a custom bullet icon, or a styled selection state can each add character with a single CSS change. show only if there are basic bullet points in page. together with image249.' },
    { src: 'image249.jpeg', pair: 'image248.png', tags: ['Visual Hierarchy'], desc: 'used to show how custom icon bullets transform a plain list. Custom icon bullets replace default browser dots and add personality without structural changes.' },
    { src: 'image250.jpeg', tags: ['Typography'], desc: 'used to show how an oversized decorative quote mark transforms a testimonial. An oversized decorative quotation mark transforms a plain testimonial text block into a designed component. show only if there are testimonials in the page.' },
    { src: 'image251.jpeg', tags: ['Typography', 'Interactive Targets'], desc: 'used to show how Links are another great candidate for special styling. You can do something as simple as changing the color and font weight, or something as fancy as a thick and colorful custom underline that partially overlaps the text. show only if there are links in the texts with no styling.' },
    { src: 'image252.png', tags: ['Visual Hierarchy'], desc: 'used to show how on a form, using custom checkboxes and radio buttons is an easy way to add some color to the design. shown only if there is checkboxes and radio buttons with no styling in the page.' },
    { src: 'image258.png', pair: 'image259.png', tags: ['Spacing & Layout', 'Visual Hierarchy'], desc: 'used to show how a contrasting background fill separates panels without borders. A contrasting background fill alone is enough to visually separate a panel from adjacent content without borders or shadows. show if there are 4+ elements/containers/cards on the page with basic white background.' },
    { src: 'image259.png', pair: 'image258.png', tags: ['Spacing & Layout', 'Visual Hierarchy'], desc: 'used to show how a subtle gradient background adds depth to a flat panel. A subtle top-to-bottom gradient adds visual energy and perceived depth to what would otherwise be a flat panel. show this if the page has 3+ same background-colored sections.' },

    // ── Balance ───────────────────────────────────────────────────────────────
    { src: 'image277.jpg', pair: 'image281.jpg', tags: ['Spacing & Layout', 'Visual Weight'], desc: 'used to show how a small high-contrast CTA button counterbalances a large hero photo in a LEFT-RIGHT split layout. ONLY use this image when the finding is about LEFT-RIGHT (horizontal) imbalance where one side of the layout is heavier than the other — for example a large image on the left and thin text on the right. Do NOT use for top-to-bottom or vertical imbalance findings. Shown together with image281 and image282.' },
    { src: 'image281.jpg', pair: 'image282.jpg', tags: ['Spacing & Layout', 'Visual Weight'], desc: 'used to show how a left-heavy split layout creates visual tension. The centered text here establishes symmetrical balance on a vertical axis, but the left side is visually heavier, creating tension. ONLY use when the finding is about LEFT-RIGHT (horizontal) imbalance — one side feels heavier than the other. Do NOT use for top-to-bottom or vertical imbalance findings. Shown together with image282 and image277.' },
    { src: 'image282.jpg', pair: 'image281.jpg', tags: ['Spacing & Layout', 'Visual Weight'], desc: 'used to show balanced placement of text and buttons in a left-right layout. Only shown together with image281 when the finding is about horizontal (left-right) imbalance.' },
];

/**
 * Fast lookup map for server-side validation of AI-returned filenames.
 * @type {Record<string, BookImageEntry>}
 */
export const BOOK_IMAGE_MAP = Object.fromEntries(
    BOOK_IMAGES.map(img => [img.src, img])
);

/**
 * Compact string sent to the AI — one line per image.
 * The AI uses this to pick 0-2 images per finding.
 */
export const BOOK_IMAGES_PROMPT_LIST = BOOK_IMAGES
    .map(img => `${img.src}${img.pair ? ` [PAIR WITH ${img.pair}]` : ''}: ${img.desc}`)
    .join('\n');
